export const REGISTER_USER='REGISTER_USER';
export const LOGIN_USER='LOGIN_USER';
export const GET_USER_LOAD='GET_USER_LOAD'
export const GET_USER='GET_USER';
export const GET_USER_FAIL='GET_USER_FAIL'
export const LOGOUT_USER='LOGOUT_USER';
export const LOAD_USER=' LOAD_USER';
export const FAIL_USER='FAIL_USER';
export const CURRENT_USER='CURRENT_USER';
export const TOGLLE_TRUE='TOGLLE_TRUE';
export const TOGLLE_FALSE='TOGLLE_FALSE';
